### ISSUE TITLE
cran submission

### ISSUE THREAD

**Issue by mpadge** [mpadge/typetracer#11]
> Thanks,
>
> Please do not start the description with "This package", package name, title or similar.
>
> Please write references in the description of the DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: authors (year) [<https:...>](https://github.com/mpadge/typetracer/issues/...)
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for auto-linking.
(If you want to add a title as well please put it in quotes: "Title")
>
> Please always write package names, software names and API (application programming interface) names in single quotes in title and description. e.g: --> 'R'
>
>Please add \value to .Rd files regarding exported methods and explain the functions results in the documentation. Please write about the structure of the output (class) and also what the output means. (If a function does not return a value, please document that too, e.g. \value{No return value, called for side effects} or similar)
Missing Rd-tags:
     clear_traces.Rd:  \value
     load_traces.Rd: \value
>
> Please ensure that your functions do not write by default or in your examples/vignettes/tests in the user's home filespace (including the package directory and getwd()). This is not allowed by CRAN policies.
Please omit any default path in writing functions. In your examples/vignettes/tests you can write to tempdir().
>
> Please do not install packages in your functions, examples or vignette. This can make the functions,examples and cran-check very slow.
>
> Please fix and resubmit.

---

### TODO

- [x] ~~Rm "This package" reference from Description~~ (False positive)
- [x] Fix citation format in Description
- [x] Put all refs to package and software names in Description in single quotes.
- [x] Add missing \value tags to `clear_traces()`
- [x] Add missing \value tags to `load_traces()`
- [x] ~~Check which examples/tests write in home filespace?~~ (False positive?; done by next point anyway.)
- [x] Switch off tests/examples of `trace_package()` which install packages.
- [x] Write "cran-comments.md" explaining everything that's been done

**Comment by mpadge** [comment]
Nothing should have writting in the home filespace, but switching off all tests which installed packages has greatly reduced numbers of CRAN tests anyway, so hopefully that should be fine now anyway.

**Comment by mpadge** [comment]
> Thanks,
>
> While your package does not start with "This package", it does with your title. Please omit the first sentence of your description.
>
> You still have one 'R' not in single quotes. Please add them as well.
>
> Please fix and resubmit. 

## TODO

- [ ] Remove first sentence from description
- [ ] Fix non-quoted "R"
